# Generated by Django 3.1.3 on 2020-11-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Image',
        ),
    ]
