# Generated by Django 3.1.3 on 2020-11-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employees_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Image',
            field=models.ImageField(default='', upload_to='gallery'),
        ),
    ]
