# Generated by Django 3.1.3 on 2020-11-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Phone',
            field=models.IntegerField(default=35354365),
        ),
    ]
